#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# =============================================================================
#
#  GIAR Simulation Pipeline for LiDAR (GSPL)
#
#  GSPL-02_Simulation_Compiler.py
#
#  Version : 1.0.0   Stable
#
#  Description
#  -----------
#  Reads the Engineering Assembly Table generated by GSPL-01,
#  validates the engineering information and generates the
#  Simulation Database used by the remaining stages.
#
#  Input
#  -----
#      config.json
#      1_model_database.json
#      1_assembly.json
#      1_assembly_table.xlsx
#
#  Output
#  ------
#       "simulation_database": "2_simulation_database.json"
#       "simulation_report": "2_simulation_report.md"
#       "assembly_table_output": "2_assembly_table.xlsx"
#
#  Author
#  ------
#      GIAR - Grupo de Inteligencia Artificial y Robótica
#      Universidad Tecnológica Nacional
#
# =============================================================================

import os
import json
import logging
import openpyxl
from openpyxl import load_workbook
from openpyxl.styles import PatternFill
from openpyxl.styles import Font
from openpyxl.styles import Alignment
from openpyxl.styles import Border, Side
from openpyxl.utils import get_column_letter
from enum import Enum
from copy import copy, deepcopy
import shutil
from datetime import datetime




# =============================================================================
# Audit Codes
# =============================================================================
class AuditCode(Enum):

    # --------------------------------------------------
    # Components Sheet
    # --------------------------------------------------

    ASM001 = "ASM-001"     # Missing Component ID
    ASM002 = "ASM-002"     # Missing Component Name
    ASM003 = "ASM-003"     # Component not found in Model Database
    ASM004 = "ASM-004"     # Duplicated Component Name
    ASM005 = "ASM-005"     # Duplicated Component ID

    # --------------------------------------------------
    # Objects Sheet
    # --------------------------------------------------

    ASM010 = "ASM-010"     # Unknown Component ID
    ASM011 = "ASM-011"     # Missing Object Name
    ASM012 = "ASM-012"     # Unsupported Object Type

    # --------------------------------------------------
    # Hierarchy
    # --------------------------------------------------

    ASM020 = "ASM-020"     # Invalid Parent Name
    ASM021 = "ASM-021"     # Disabled Component
    ASM022 = "ASM-022"     # Parent Loop
    ASM023 = "ASM-023"     # Parent Not Found

    # --------------------------------------------------
    # Objects Validation
    # --------------------------------------------------

    ASM030 = "ASM-030"     # Root Component
    ASM031 = "ASM-031"     # Parent Exists
    ASM032 = "ASM-032"     # Duplicate Name
    ASM033 = "ASM-033"     # Duplicate ID
    ASM034 = "ASM-034"
    ASM035 = "ASM-035"
    ASM036 = "ASM-036"
    ASM037 = "ASM-037"
    ASM038 = "ASM-038"

# =============================================================================
# Audit Message
# =============================================================================
class AuditMessage:
    """
    Represents a validation or audit message generated during the GSPL pipeline.
    """

    def __init__(
        self,
        code: str,
        severity: str,
        message: str,
        component: str = "",
        object_name: str = ""
    ):

        self.code = code
        self.severity = severity.upper()
        self.component = component
        self.object_name = object_name
        self.message = message

    # ------------------------------------------------------------------
    # String Representation
    # ------------------------------------------------------------------
    def __str__(self):

        text = f"[{self.code}] {self.severity}"
        if self.component:
            text += f" | Component: {self.component}"

        if self.object_name:
            text += f" | Object: {self.object_name}"

        text += f" | {self.message}"

        return text

    # ------------------------------------------------------------------
    # Dictionary Representation
    # ------------------------------------------------------------------
    def to_dict(self):

        return {

            "code": self.code,

            "severity": self.severity,

            "component": self.component,

            "object": self.object_name,

            "message": self.message

        }
    
# =============================================================================
# Simulation Compiler
# =============================================================================
class SimulationCompiler:
    VERSION = "1.0.0"
    CHECK_COLUMN_WIDTH = 16
    MESSAGE_COLUMN_WIDTH = 50

    # -------------------------------------------------------------------------
    # Constructor
    # -------------------------------------------------------------------------
    def __init__(self):
        self.config = {}
        self.logger = None
        self.model_database = {}
        self.assembly_json = {}
        self.simulation_database = {}
        self.model_components_by_id = {}
        self.model_components_by_name = {}
        self.components_by_id = {}
        self.components_by_name = {}
        self.assembly_components_by_id = {}
        self.assembly_components_by_name = {}
        self.workbook = None
        self.components_sheet = None
        self.objects_sheet = None
        self.audit_messages = []
        self.statistics = {
            "components": 0,
            "objects": 0,
            "warnings": 0,
            "errors": 0
        }
        self.check_styles = {
            "OK": PatternFill(
                fill_type="solid",
                fgColor="C6EFCE"
            ),
            "WARNING": PatternFill(
                fill_type="solid",
                fgColor="FFF2CC"
            ),
            "ERROR": PatternFill(
                fill_type="solid",
                fgColor="F4CCCC"
            ),
            "DISABLED": PatternFill(
                fill_type="solid",
                fgColor="D9D9D9"
            )
        }
        self.self_test_passed = False

    # -------------------------------------------------------------------------
    # Main Pipeline
    # -------------------------------------------------------------------------
    def run(self):

        # --------------------------------------------------
        # Initialization
        # --------------------------------------------------
        self.load_configuration()
        self.initialize_logger()

        # --------------------------------------------------
        # Load Input Files
        # --------------------------------------------------
        self.load_model_database()
        self.load_assembly_template()
        self.load_assembly_table()

        # --------------------------------------------------
        # Load Engineering Data
        # --------------------------------------------------
        self.load_components_sheet()
        self.load_objects_sheet()

        # --------------------------------------------------
        # Build Internal Indexes
        # --------------------------------------------------
        self.build_component_indexes()
        self.build_object_indexes()

        # --------------------------------------------------
        # Validate Engineering Data
        # --------------------------------------------------
        self.validate_components_sheet()
        self.validate_objects_sheet()
        
        # --------------------------------------------------
        # Resolve Component Hierarchy
        # --------------------------------------------------
        self.resolve_parent_ids()

        # --------------------------------------------------
        # Run Validation Audits
        # --------------------------------------------------
        self.run_audits()

        # --------------------------------------------------
        # Update Component Status
        # --------------------------------------------------
        self.update_component_check()
        self.update_object_check()

        # --------------------------------------------------
        # Generate Engineering Output
        # --------------------------------------------------
        self.generate_engineering_table()

        # --------------------------------------------------
        # Build Output Database
        # --------------------------------------------------
        self.compile_simulation_database()

        # --------------------------------------------------
        # Save Output Files
        # --------------------------------------------------
        self.save_simulation_database()

        # --------------------------------------------------
        # Reports
        # --------------------------------------------------
        self.print_statistics()
        self.generate_report()

        # --------------------------------------------------
        # Tested
        # --------------------------------------------------
        self.self_test()

        # --------------------------------------------------
        # Finish
        # --------------------------------------------------
        self.finish()

    # -------------------------------------------------------------------------
    # Load Configuration
    # ------------------------------------------------------------------------
    def load_configuration(self):

        config_file = "config.json"

        if not os.path.exists(config_file):

            raise FileNotFoundError(
                f"Configuration file not found: {config_file}"
            )

        with open(config_file, "r", encoding="utf-8") as f:

            self.config = json.load(f)

    # -------------------------------------------------------------------------
    # Initialize Logger
    # -------------------------------------------------------------------------
    def initialize_logger(self):

        self.logger = logging.getLogger(__name__)

        self.logger.setLevel(logging.INFO)

        # Evita duplicar mensajes si se ejecuta más de una vez
        self.logger.handlers.clear()

        console = logging.StreamHandler()

        console.setLevel(logging.INFO)

        console.setFormatter(
            logging.Formatter("%(message)s")
        )

        self.logger.addHandler(console)

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" GSPL-02 Simulation Compiler")
        self.logger.info("========================================================")
        self.logger.info(" Author:")
        self.logger.info("     Ing. Pablo Daniel Folino")
        self.logger.info("====================================================")
        self.logger.info("Version : %s", self.VERSION)
        self.logger.info("")

    # -------------------------------------------------------------------------
    # Load Model Database
    # -------------------------------------------------------------------------
    def load_model_database(self):
        self.logger.info("")
        self.logger.info("Loading Model Database...")
        filename = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["model_database"]
        )
        if not os.path.exists(filename):
            raise FileNotFoundError(
                f"Model database not found:\n{filename}"
            )
        with open(filename, "r", encoding="utf-8") as f:
            self.model_database = json.load(f)

        # --------------------------------------------------
        # Build Model Database Indexes
        # --------------------------------------------------
        components = self.model_database.get("components", [])
        self.model_components_by_id = {}
        self.model_components_by_name = {}
        for component in components:
            self.model_components_by_id[component["id"]] = component
            self.model_components_by_name[component["name"]] = component

        component_count = len(components)
        self.statistics["components"] = component_count
        self.logger.info("OK")
        self.logger.info("Components : %d", component_count)
        self.logger.info(
            "Model Indexes : %d IDs | %d Names",
            len(self.model_components_by_id),
            len(self.model_components_by_name)
        )

    # -------------------------------------------------------------------------
    # Load Assembly Template
    # -------------------------------------------------------------------------
    def load_assembly_template (self):
        self.logger.info("")
        self.logger.info("Loading Assembly Template...")
        filename = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["assembly"]
        )
        if not os.path.exists(filename):
            raise FileNotFoundError(
                f"Assembly template not found:\n{filename}"
            )
        with open(filename, "r", encoding="utf-8") as f:
            self.assembly_json = json.load(f)
        component_count = len(
            self.assembly_json.get("components", [])
        )
        self.logger.info("OK")
        self.logger.info("Components : %d", component_count)

    # -------------------------------------------------------------------------
    # Load Engineering Table
    # -------------------------------------------------------------------------
    def load_assembly_table(self):

        self.logger.info("")
        self.logger.info("Loading Assembly Table...")

        filename = os.path.join(

            self.config["paths"]["database_directory"],

            self.config["files"]["assembly_table"]

        )

        if not os.path.exists(filename):

            raise FileNotFoundError(

                f"Assembly table not found:\n{filename}"

            )

        self.workbook = load_workbook(

            filename=filename,

            data_only=True

        )

        self.check_required_sheets()

        self.components_sheet = self.workbook["Components"]

        self.objects_sheet = self.workbook["Objects"]

        self.logger.info("OK")

        self.logger.info(

            "Worksheets : %d",

            len(self.workbook.sheetnames)

        )

        self.logger.info(

            "Components Rows : %d",

            self.components_sheet.max_row - 1

        )

        self.logger.info(

            "Objects Rows : %d",

            self.objects_sheet.max_row - 1

        )

    # -------------------------------------------------------------------------
    # Check Required Worksheets
    # -------------------------------------------------------------------------
    def check_required_sheets(self):

        required = [

            "Components",

            "Objects"

        ]

        missing = [

            sheet

            for sheet in required

            if sheet not in self.workbook.sheetnames

        ]

        if missing:

            raise RuntimeError(

                "Missing worksheet(s): "

                + ", ".join(missing)

            )
    
    # -------------------------------------------------------------------------
    # Load Components Sheet
    # -------------------------------------------------------------------------
    def load_components_sheet(self):
        self.logger.info("")
        self.logger.info("Loading Components Sheet...")
        self.components = {}
        row = 2
        while True:
            component_id = self.components_sheet.cell(row=row, column=1).value
            if component_id is None:
                break
            component = {
                "id": component_id,
                "name": self.components_sheet.cell(row=row, column=2).value,
                "type": self.components_sheet.cell(row=row, column=3).value,
                "description": self.components_sheet.cell(row=row, column=4).value,
                "enabled": self.components_sheet.cell(row=row, column=5).value,
                "parent_name": self.components_sheet.cell(row=row, column=6).value,
                "parent_id": self.components_sheet.cell(row=row, column=7).value,
                "visual": self.components_sheet.cell(row=row, column=8).value,
                "simulation": self.components_sheet.cell(row=row, column=9).value,
                "reviewed": self.components_sheet.cell(row=row, column=10).value,
                "status": self.components_sheet.cell(row=row, column=11).value,
                # --------------------------------------------------
                # GSPL Internal Fields
                # --------------------------------------------------
                "check": None,
                "messages": []            
            }
            self.components[component_id] = component
            row += 1
        self.logger.info("OK")
        self.logger.info(
            "Components Loaded : %d",
            len(self.components)
        )
        
    # -------------------------------------------------------------------------
    # Load Objects Sheet
    # -------------------------------------------------------------------------
    def load_objects_sheet(self):

        self.logger.info("")
        self.logger.info("Loading Objects Sheet...")

        self.objects = {}

        row = 2

        while True:

            component_id = self.objects_sheet.cell(row=row, column=1).value

            if component_id is None:

                break

            obj = {

                "component_id": component_id,

                "component_name": self.objects_sheet.cell(row=row, column=2).value,

                "object_name": self.objects_sheet.cell(row=row, column=3).value,

                "object_type": self.objects_sheet.cell(row=row, column=4).value,

                "enabled": self.objects_sheet.cell(row=row, column=5).value,

                "position": [

                    self.objects_sheet.cell(row=row, column=6).value,

                    self.objects_sheet.cell(row=row, column=7).value,

                    self.objects_sheet.cell(row=row, column=8).value

                ],

                "orientation": [

                    self.objects_sheet.cell(row=row, column=9).value,

                    self.objects_sheet.cell(row=row, column=10).value,

                    self.objects_sheet.cell(row=row, column=11).value

                ],

                "joint_type": self.objects_sheet.cell(row=row, column=18).value,

                "cyclic": self.objects_sheet.cell(row=row, column=19).value,

                "lower_limit": self.objects_sheet.cell(row=row, column=20).value,

                "upper_limit": self.objects_sheet.cell(row=row, column=21).value,

                "motor": self.objects_sheet.cell(row=row, column=22).value,

                "notes": self.objects_sheet.cell(row=row, column=23).value,

                # --------------------------------------------------
                # GSPL Internal Fields
                # --------------------------------------------------

                "check": None,

                "messages": []
            }

            self.objects.setdefault(component_id, []).append(obj)

            row += 1

        self.logger.info("OK")

        self.logger.info(

            "Objects Loaded : %d",

            sum(len(v) for v in self.objects.values())

        )

    # -------------------------------------------------------------------------
    # Build Component Indexes
    # -------------------------------------------------------------------------
    def build_component_indexes(self):

        self.logger.info("")
        self.logger.info("Building Component Indexes...")

        self.components_by_id = {}

        self.components_by_name = {}

        for component in self.components.values():

            self.components_by_id[component["id"]] = component

            self.components_by_name[component["name"]] = component

        self.logger.info("OK")

        self.logger.info(
            "Component IDs   : %d",
            len(self.components_by_id)
        )

        self.logger.info(
            "Component Names : %d",
            len(self.components_by_name)
        )

    # -------------------------------------------------------------------------
    # Build Object Indexes
    # -------------------------------------------------------------------------
    def build_object_indexes(self):
        self.logger.info("")
        self.logger.info("Building Object Indexes...")
        self.objects_by_component = self.objects
        self.logger.info("OK")
        self.logger.info(
            "Indexed Components : %d",
            len(self.objects_by_component)
        )

    # -------------------------------------------------------------------------
    # Validate Components Sheet
    # -------------------------------------------------------------------------
    def validate_components_sheet(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Validating Components Sheet")
        self.logger.info("========================================================")

        ids = set()
        names = set()

        for component in self.components.values():

            # --------------------------------------------------
            # ASM-001
            # --------------------------------------------------

            if component["id"] is None:

                self.register_component_audit(
                    component_name="",
                    code=AuditCode.ASM001.value,
                    severity="ERROR",
                    message="Missing Component ID."
                )

            # --------------------------------------------------
            # ASM-002
            # --------------------------------------------------

            if not component["name"]:

                self.register_component_audit(
                        component_name="",
                        code=AuditCode.ASM002.value,
                        severity="ERROR",
                        message="Missing Component Name."
               )

            # --------------------------------------------------
            # ASM-003
            # Verify that the component exists in the
            # Model Database generated by GSPL-01.
            # --------------------------------------------------

            elif component["name"] not in self.model_components_by_name:

                self.register_component_audit(
                        component_name=component["name"],
                        code=AuditCode.ASM003.value,
                        severity="ERROR",
                        message="Component not found in Model Database."
                )

            # --------------------------------------------------
            # ASM-004
            # --------------------------------------------------

            if component["name"] in names:

                self.register_component_audit(
                        component_name=component["name"],
                        code=AuditCode.ASM004.value,
                        severity="ERROR",
                        message="Duplicated Component Name."
                )

            names.add(component["name"])

            # --------------------------------------------------
            # ASM-005
            # --------------------------------------------------

            if component["id"] in ids:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM005.value,
                    severity="ERROR",
                    message="Duplicated Component ID."
                )

            ids.add(component["id"])

        self.logger.info("Validation Finished")
        self.logger.info(
            "Messages : %d",
            len(self.audit_messages)
        )

    # -------------------------------------------------------------------------
    # Validate Objects Sheet
    # -------------------------------------------------------------------------
    def validate_objects_sheet(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Validating Objects Sheet")
        self.logger.info("========================================================")

        valid_types = {
            "shape",
            "dummy",
            "joint",
            "camera",
            "force_sensor",
            "vision_sensor",
            "proximity_sensor"
        }

        for component_id, objects in self.objects.items():

            for obj in objects:

                # --------------------------------------------------
                # ASM-011
                # Missing Object Name
                # --------------------------------------------------

                if not obj["object_name"]:

                    self.register_object_audit(
                        obj=obj,
                        code=AuditCode.ASM011.value,
                        severity="ERROR",
                        message="Missing Object Name."
                    )

                # --------------------------------------------------
                # Normalize Object Type
                # --------------------------------------------------

                object_type = self.normalize_object_type(
                    obj["object_type"]
                )

                obj["object_type"] = object_type

                # --------------------------------------------------
                # ASM-012
                # Unsupported Object Type
                # --------------------------------------------------

                if object_type not in valid_types:

                    self.register_object_audit(
                        obj=obj,
                        code=AuditCode.ASM012.value,
                        severity="ERROR",
                        message=f"Unsupported Object Type '{obj['object_type']}'."
                    )

        self.logger.info("Validation Finished")

        self.logger.info(
            "Messages : %d",
            len(self.audit_messages)
        )

    # -------------------------------------------------------------------------
    # Resolve Parent IDs
    # -------------------------------------------------------------------------
    def resolve_parent_ids(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Resolving Parent IDs")
        self.logger.info("========================================================")

        resolved = 0

        for component in self.components.values():

            component_name = component["name"]

            parent_name = component["parent_name"]

            # --------------------------------------------------
            # Root Component
            # --------------------------------------------------

            if parent_name is None or str(parent_name).strip() == "":

                component["parent_id"] = None

                continue

            # --------------------------------------------------
            # ASM-020
            # Parent component does not exist
            # --------------------------------------------------

            if parent_name not in self.model_components_by_name:

                self.register_component_audit(
                    component_name=component_name,
                    code=AuditCode.ASM020.value,
                    severity="ERROR",
                    message=f"Unknown parent component '{parent_name}'."
                )

                component["parent_id"] = None

                continue

            # --------------------------------------------------
            # Parent Component
            # --------------------------------------------------

            parent = self.components_by_name[parent_name]

            # --------------------------------------------------
            # ASM-021
            # Component cannot be parent of itself
            # --------------------------------------------------

            if parent["id"] == component["id"]:

                self.register_component_audit(
                    component_name=component_name,
                    code=AuditCode.ASM021.value,
                    severity="ERROR",
                    message="Component cannot be parent of itself."
                )

                component["parent_id"] = None

                continue

            # --------------------------------------------------
            # ASM-023
            # Parent component disabled
            # --------------------------------------------------

            if not parent["enabled"]:

                self.register_component_audit(
                        component_name=component_name,
                        code=AuditCode.ASM023.value,
                        severity="WARNING",
                        message=f"Parent component '{parent_name}' is disabled."
                )

            # --------------------------------------------------
            # Copy Parent ID
            # --------------------------------------------------

            component["parent_id"] = parent["id"]

            resolved += 1

        self.logger.info("OK")

        self.logger.info(
            "Resolved Parent IDs : %d",
            resolved
        )

    # -------------------------------------------------------------------------
    # Find Component By Name
    # -------------------------------------------------------------------------
    def find_component_by_name(self, component_name):
        """
        Returns the component dictionary matching the given name,
        or None if it does not exist.
        """
        for component in self.simulation_database["components"]:
            if component["name"] == component_name:
               return component
        return None

    # -------------------------------------------------------------------------
    # Compile Simulation Database
    # -------------------------------------------------------------------------
    def compile_simulation_database(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Compiling Simulation Database")
        self.logger.info("========================================================")

        now = datetime.now()

        exported = 0
        skipped = 0

        # --------------------------------------------------
        # Create Database Header
        # --------------------------------------------------

        self.simulation_database = {

            "format_version": "1.0",

            "generated_by": "GSPL-02_Simulation_Compiler",

            "generator_version": self.VERSION,

            "generated": {

                "date": now.strftime("%Y-%m-%d"),

                "time": now.strftime("%H:%M:%S")

            },

            "project": self.config["project"]["name"],

            "root": None,

            "statistics": {},

            "components": []

        }

        # --------------------------------------------------
        # Process Components
        # --------------------------------------------------

        for assembly_component in self.assembly_json["components"]:

            name = assembly_component["name"]

            # --------------------------------------------------
            # Component must exist in Engineering Table
            # --------------------------------------------------

            if name not in self.components_by_name:

                self.logger.warning(
                    "Component '%s' not found in Engineering Table.",
                    name
                )

                skipped += 1

                continue

            engineering = self.components_by_name[name]

            # --------------------------------------------------
            # Export only validated components
            # --------------------------------------------------

            check = engineering.get("check", "ERROR")

            if check not in ("OK", "WARNING"):

                self.logger.info(
                    "Skipping %-30s [%s]",
                    name,
                    check
                )

                skipped += 1

                continue

            # --------------------------------------------------
            # Copy Component
            # --------------------------------------------------

            component = deepcopy(assembly_component)

            # --------------------------------------------------
            # Engineering Parameters
            # --------------------------------------------------

            component["parent"] = engineering.get("parent_id")

            component["enabled"] = engineering.get("enabled", True)

            component["visual"] = engineering.get("visual", True)

            component["simulation"] = engineering.get("simulation", True)

            component["description"] = engineering.get(
                "description",
                ""
            )

            component["reviewed"] = engineering.get(
                "reviewed",
                False
            )

            component["status"] = engineering.get(
                "status",
                "NEW"
            )

            # --------------------------------------------------
            # Validation Information
            # --------------------------------------------------

            component["check"] = engineering.get(
                "check",
                "OK"
            )

            component["messages"] = deepcopy(
                engineering.get("messages", [])
            )

            # --------------------------------------------------
            # Engineering Type
            # --------------------------------------------------

            component["type"] = engineering.get(

                "type",

                component.get("type", "Mechanical")

            )

            # --------------------------------------------------
            # Model Selection
            # --------------------------------------------------

            models = []

            if engineering.get("visual", True):

                models.append("visual")

            if engineering.get("simulation", True):

                models.append("simulation")

            component["models"] = models

            # --------------------------------------------------
            # Store Component
            # --------------------------------------------------

            self.simulation_database["components"].append(component)

            exported += 1

        # --------------------------------------------------
        # Root Component
        # --------------------------------------------------

        root_id = None

        for component in self.simulation_database["components"]:

            if component["parent"] is None:

                root_id = component["id"]

                break

        self.simulation_database["root"] = root_id

        # --------------------------------------------------
        # Statistics
        # --------------------------------------------------

        statistics = {

            "components": 0,

            "mechanical": 0,

            "electronic": 0,

            "sensor": 0,

            "actuator": 0,

            "enabled": 0,

            "disabled": 0,

            "visual": 0,

            "simulation": 0,

            "exported": exported,

            "skipped": skipped

        }

        for component in self.simulation_database["components"]:

            statistics["components"] += 1

            ctype = component["type"]

            if ctype == "Mechanical":

                statistics["mechanical"] += 1

            elif ctype == "Electronic":

                statistics["electronic"] += 1

            elif ctype == "Sensor":

                statistics["sensor"] += 1

            elif ctype == "Actuator":

                statistics["actuator"] += 1

            if component["enabled"]:

                statistics["enabled"] += 1

            else:

                statistics["disabled"] += 1

            if component["visual"]:

                statistics["visual"] += 1

            if component["simulation"]:

                statistics["simulation"] += 1

        self.simulation_database["statistics"] = statistics

        # --------------------------------------------------
        # Log Summary
        # --------------------------------------------------

        self.logger.info("OK")

        self.logger.info(
            "Root Component       : %s",
            root_id
        )

        self.logger.info(
            "Exported Components  : %d",
            exported
        )

        self.logger.info(
            "Skipped Components   : %d",
            skipped
        )

        self.logger.info(
            "Database Components  : %d",
            len(self.simulation_database["components"])
        )

    # -------------------------------------------------------------------------
    # Save Simulation Database
    # -------------------------------------------------------------------------
    def save_simulation_database (self):
        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Saving Simulation Database")
        self.logger.info("========================================================")
        filename = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["simulation_database"]
        )
        os.makedirs(
            os.path.dirname(filename),
            exist_ok=True
        )
        with open(
            filename,
            "w",
            encoding="utf-8"
        ) as f:
            json.dump(
                self.simulation_database,
                f,
                indent=4,
                ensure_ascii=False
            )
        component_count = len(
            self.simulation_database.get("components", [])
        )
        self.logger.info("OK")
        self.logger.info(
            "Components : %d",
            component_count
        )
        self.logger.info(
            "File : %s",
            filename
        )

    # -------------------------------------------------------------------------
    # Print Statistics
    # -------------------------------------------------------------------------
    def print_statistics(self):

        warnings = 0
        errors = 0

        for audit in self.audit_messages:

            if audit.severity == "WARNING":
                warnings += 1

            elif audit.severity == "ERROR":
                errors += 1

        self.statistics["warnings"] = warnings
        self.statistics["errors"] = errors

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Statistics")
        self.logger.info("========================================================")

        self.logger.info(
            "Components : %d",
            len(self.components)
        )

        self.logger.info(
            "Objects    : %d",
            sum(len(v) for v in self.objects.values())
        )

        self.logger.info(
            "Warnings   : %d",
            warnings
        )

        self.logger.info(
            "Errors     : %d",
            errors
        )

   # -------------------------------------------------------------------------
    # Audits
    # -------------------------------------------------------------------------
    def run_audits(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Running Validation Audits")
        self.logger.info("========================================================")

        self.audit_root_component()

        self.audit_parent_exists()

        self.audit_duplicate_component_names()

        self.audit_duplicate_component_ids()

        self.audit_objects_reference()

        self.audit_empty_objects()

        self.audit_bounding_box()

        self.audit_frame()

        self.audit_models()

        self.logger.info("Validation completed.")

    # -------------------------------------------------------------------------
    # Register Component Audit
    # -------------------------------------------------------------------------
    def register_component_audit(
        self,
        component_name,
        code,
        severity,
        message,
        object_name=""
    ):

        # --------------------------------------------------
        # Global Audit List
        # --------------------------------------------------

        audit = AuditMessage(
            code=code,
            severity=severity,
            component=component_name,
            object_name=object_name,
            message=message

        )

        self.audit_messages.append(audit)

        # --------------------------------------------------
        # Component Not Found
        # --------------------------------------------------

        if component_name not in self.components_by_name:
            return

        component = self.components_by_name[component_name]

        # --------------------------------------------------
        # Store Message
        # --------------------------------------------------

        component["messages"].append({
            "code": code,
            "severity": severity,
            "object": object_name,
            "message": message

        })

        # --------------------------------------------------
        # Update Check Status
        # --------------------------------------------------

        current = component["check"]

        if severity == "ERROR":

            component["check"] = "ERROR"

        elif severity == "WARNING":

            if current != "ERROR":

                component["check"] = "WARNING"
   
    # -------------------------------------------------------------------------
    # ASM-030
    # Root Component
    # -------------------------------------------------------------------------
    def audit_root_component(self):

        roots = []

        for component in self.components.values():

            if component["parent_id"] is None:

                roots.append(component)

        # --------------------------------------------------
        # Exactly one Root
        # --------------------------------------------------

        if len(roots) == 1:

            self.logger.info(
                "ASM-030 PASS - Root Component : %s",
                roots[0]["name"]
            )

            return

        # --------------------------------------------------
        # No Root
        # --------------------------------------------------

        if len(roots) == 0:

            self.register_component_audit(
                component_name="",
                code=AuditCode.ASM030.value,
                severity="ERROR",
                message="No Root Component found."
            )

            return

        # --------------------------------------------------
        # Hierarchy Incomplete
        # --------------------------------------------------

        names = ", ".join(
            component["name"]
            for component in roots
        )

        self.register_component_audit(
            component_name="",
            code=AuditCode.ASM030.value,
            severity="WARNING",
            message=(
                f"Hierarchy incomplete. "
                f"{len(roots)} components have no parent assigned: "
                f"{names}."
            )
        )

    # -------------------------------------------------------------------------
    # ASM-031
    # Parent Component Exists
    # -------------------------------------------------------------------------
    def audit_parent_exists(self):

        for component in self.components.values():

            parent = component.get("parent_name")

            if not parent:

                continue

            if parent not in self.model_components_by_name:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM031.value,
                    severity="ERROR",
                    message=f"Parent '{parent}' does not exist."

                )

    # -------------------------------------------------------------------------
    # ASM-032
    # Duplicate Component Names
    # -------------------------------------------------------------------------
    def audit_duplicate_component_names(self):

        names = set()

        for component in self.components.values():

            name = component["name"]

            if name in names:

                self.register_component_audit(
                    component_name=name,
                    code=AuditCode.ASM032.value,
                    severity="ERROR",
                    message="Duplicate Component Name."
                )

            names.add(name)

    # -------------------------------------------------------------------------
    # ASM-033
    # Duplicate Component IDs
    # -------------------------------------------------------------------------
    def audit_duplicate_component_ids(self):

        ids = set()

        for component in self.components.values():

            cid = component["id"]

            if cid in ids:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM033.value,
                    severity="ERROR",
                    message=f"Duplicate Component ID ({cid})."
                )

            ids.add(cid)

    # -------------------------------------------------------------------------
    # ASM-034
    # Objects Reference
    # -------------------------------------------------------------------------
    def audit_objects_reference(self):

        for component_id, objects in self.objects.items():

            # --------------------------------------------------
            # Component ID exists
            # --------------------------------------------------

            if component_id in self.components:
                continue

            # --------------------------------------------------
            # Unknown Component ID
            # --------------------------------------------------

            for obj in objects:

                candidate = self.components_by_name.get(
                    obj["component_name"]
                )

                if candidate is not None:

                    message = (
                        f"Unknown Component ID {component_id}. "
                        f"Component '{obj['component_name']}' exists with "
                        f"Component ID {candidate['id']}. "
                        f"Suggested Fix: change Component ID to {candidate['id']}."
                    )

                else:

                    message = (
                        f"Unknown Component ID {component_id}. "
                        f"Component '{obj['component_name']}' does not exist."
                    )

                self.register_object_audit(
                    obj=obj,
                    code=AuditCode.ASM034.value,
                    severity="ERROR",
                    message=message
                )

    # -------------------------------------------------------------------------
    # ASM-035
    # Component without Objects
    # -------------------------------------------------------------------------
    def audit_empty_objects(self):

        for component in self.components.values():

            if component["id"] not in self.objects:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM035.value,
                    severity="WARNING",
                    message="Component has no objects."
                )

    # -------------------------------------------------------------------------
    # ASM-036
    # Bounding Box Exists
    # -------------------------------------------------------------------------
    def audit_bounding_box(self):

        for component in self.model_database["components"]:

            if component.get("bounding_box") is None:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM036.value,
                    severity="WARNING",
                    message="Bounding Box not defined."
                )

    # -------------------------------------------------------------------------
    # ASM-037
    # Frame Exists
    # -------------------------------------------------------------------------
    def audit_frame(self):

        for component in self.assembly_json["components"]:

            if component.get("frame") is None:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM037.value,
                    severity="WARNING",
                    message="Frame not defined."
                )

    # -------------------------------------------------------------------------
    # ASM-038
    # Models Exists
    # -------------------------------------------------------------------------
    def audit_models(self):

        for component in self.assembly_json["components"]:

            if "models" not in component:

                self.register_component_audit(
                    component_name=component["name"],
                    code=AuditCode.ASM038.value,
                    severity="WARNING",
                    message="Models section missing."
                )

    # -------------------------------------------------------------------------
    # Register Object Audit
    # -------------------------------------------------------------------------
    def register_object_audit(
        self,
        obj,
        code,
        severity,
        message
    ):

        # --------------------------------------------------
        # Global Audit List
        # --------------------------------------------------

        self.register_component_audit(
            component_name=obj["component_name"],
            code=code,
            severity=severity,
            object_name=obj["object_name"],
            message=message
        )

        # --------------------------------------------------
        # Object Messages
        # --------------------------------------------------

        obj["messages"].append({

            "code": code,

            "severity": severity,

            "message": message

        })

        # --------------------------------------------------
        # Object Check
        # --------------------------------------------------

        if severity == "ERROR":

            obj["check"] = "ERROR"

        elif severity == "WARNING":

            if obj["check"] != "ERROR":

                obj["check"] = "WARNING"

    # -------------------------------------------------------------------------
    # Update Object Check
    # -------------------------------------------------------------------------
    def update_object_check(self):

        for objects in self.objects.values():

            for obj in objects:

                if not obj["enabled"]:

                    obj["check"] = "DISABLED"

                    obj["messages"].append({

                        "code": "OBJ-000",

                        "severity": "INFO",

                        "message": "Object disabled by engineer."

                    })

                elif obj["check"] is None:

                    obj["check"] = "OK"

    # -------------------------------------------------------------------------
    # Update Component Check
    # -------------------------------------------------------------------------
    def update_component_check(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Updating Component Status")
        self.logger.info("========================================================")

        ok = 0
        warning = 0
        error = 0
        disabled = 0

        for component in self.components.values():

            # --------------------------------------------------
            # Disabled by Engineer
            # --------------------------------------------------

            if not component["enabled"]:

                component["check"] = "DISABLED"

                component["messages"].append({
                    "code": "ASM-000",
                    "severity": "INFO",
                    "message": "Component disabled by engineer."

                })

                disabled += 1

                continue

            # --------------------------------------------------
            # No Audit Messages
            # --------------------------------------------------

            if component["check"] is None:

                component["check"] = "OK"

                ok += 1

                continue

            # --------------------------------------------------
            # Statistics
            # --------------------------------------------------

            if component["check"] == "WARNING":

                warning += 1

            elif component["check"] == "ERROR":

                error += 1

        self.logger.info("OK")

        self.logger.info("OK         : %d", ok)
        self.logger.info("Warnings   : %d", warning)
        self.logger.info("Errors     : %d", error)
        self.logger.info("Disabled   : %d", disabled)

    # -------------------------------------------------------------------------
    # Copy Assembly Table
    # -------------------------------------------------------------------------
    def copy_assembly_table(self):
        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Creating Engineering Table")
        self.logger.info("========================================================")
        # --------------------------------------------------
        # Source File
        # --------------------------------------------------
        source = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["assembly_table"]
        )
        # --------------------------------------------------
        # Destination File
        # --------------------------------------------------
        destination = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["assembly_table_output"]
        )
        # --------------------------------------------------
        # Copy Workbook
        # --------------------------------------------------
        shutil.copy2(source, destination)
        self.logger.info("Source      : %s", source)
        self.logger.info("Destination : %s", destination)
        # --------------------------------------------------
        # Open Workbook
        # --------------------------------------------------
        self.workbook = openpyxl.load_workbook(destination)
        # --------------------------------------------------
        # Worksheets
        # --------------------------------------------------
        self.components_sheet = self.workbook["Components"]
        self.objects_sheet = self.workbook["Objects"]
        self.logger.info("Workbook loaded.")
        self.logger.info(
            "Components rows : %d",
            self.components_sheet.max_row
        )
        self.logger.info(
            "Objects rows    : %d",
            self.objects_sheet.max_row
        )
        self.logger.info("OK")

    # -------------------------------------------------------------------------
    # Update Components Worksheet
    # -------------------------------------------------------------------------
    def update_components_sheet(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Updating Components Worksheet")
        self.logger.info("========================================================")

        ws = self.components_sheet

        updated = 0

        # --------------------------------------------------
        # Components
        # --------------------------------------------------

        for row in range(2, ws.max_row + 1):

            component_name = ws.cell(row=row, column=2).value

            if component_name not in self.components_by_name:
                continue

            component = self.components_by_name[component_name]

            # --------------------------------------------------
            # Parent ID
            # --------------------------------------------------

            ws.cell(
                row=row,
                column=7
            ).value = component.get("parent_id")

            # --------------------------------------------------
            # Check
            # --------------------------------------------------

            check = component.get("check", "")

            cell = ws.cell(
                row=row,
                column=self.col_check
            )

            cell.value = check

            if check in self.check_styles:
                cell.fill = self.check_styles[check]

            cell.font = Font(bold=True)

            cell.alignment = Alignment(
                horizontal="center",
                vertical="center"
            )

            # --------------------------------------------------
            # Message
            # --------------------------------------------------

            messages = []

            for msg in component.get("messages", []):

                messages.append(
                    f'{msg["code"]}: {msg["message"]}'
                )

            message_cell = ws.cell(
                row=row,
                column=self.col_message
            )

            message_cell.value = "\n".join(messages)

            message_cell.alignment = Alignment(
                wrap_text=True,
                vertical="top"
            )

            # --------------------------------------------------
            # Row Height
            # --------------------------------------------------

            lines = max(1, len(messages))

            ws.row_dimensions[row].height = max(
                20,
                lines * 18
            )

            updated += 1

        # --------------------------------------------------
        # Auto Filter
        # --------------------------------------------------

        ws.auto_filter.ref = (
            f"A1:{get_column_letter(ws.max_column)}{ws.max_row}"
        )

        # --------------------------------------------------
        # Freeze Header
        # --------------------------------------------------

        ws.freeze_panes = "A2"

        self.logger.info(
            "Components Updated : %d",
            updated
        )

        self.logger.info("OK")

    # -------------------------------------------------------------------------
    # Save Assembly Table
    # -------------------------------------------------------------------------
    def save_assembly_table(self):

        filename = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["assembly_table_output"]
        )

        # --------------------------------------------------
        # Debug Components Sheet
        # --------------------------------------------------

        letter = get_column_letter(self.col_message)

        dim = self.components_sheet.column_dimensions[letter]

        self.logger.info(
            "Components -> Message column %s : width=%s customWidth=%s",
            letter,
            dim.width,
            dim.customWidth
        )

        # --------------------------------------------------
        # Debug Objects Sheet
        # --------------------------------------------------

        letter = get_column_letter(self.obj_col_message)

        dim = self.objects_sheet.column_dimensions[letter]

        self.logger.info(
            "Objects -> Message column %s : width=%s customWidth=%s",
            letter,
            dim.width,
            dim.customWidth
        )

        self.workbook.save(filename)

        self.logger.info("Engineering Table saved.")

    # -------------------------------------------------------------------------
    # Prepare Components Sheet
    # -------------------------------------------------------------------------
    def prepare_components_sheet(self):

        self.logger.info("")
        self.logger.info("Preparing Components worksheet...")

        ws = self.components_sheet

        # --------------------------------------------------
        # Insert GSPL Columns
        # --------------------------------------------------
        last_col = ws.max_column

        ws.insert_cols(last_col + 1, amount=2)
        
        self.col_check = last_col + 1
        self.col_message = last_col + 2

        # --------------------------------------------------
        # Headers
        # --------------------------------------------------
        ws.cell(row=1,column=self.col_check).value = "Check"
        ws.cell(row=1,column=self.col_message).value = "Message"
        self.apply_worksheet_format(
            worksheet=ws,
            check_col=self.col_check,
            message_col=self.col_message
        )

        # --------------------------------------------------
        # Column Width
        # --------------------------------------------------
        ws.column_dimensions[
            get_column_letter(self.col_check)
        ].width = self.CHECK_COLUMN_WIDTH

        ws.column_dimensions[
            get_column_letter(self.col_message)
        ].width = self.MESSAGE_COLUMN_WIDTH

        ws.column_dimensions[
            get_column_letter(self.col_message)
        ].bestFit = False

    # -------------------------------------------------------------------------
    # Funciones de planilla de cálculo
    # -------------------------------------------------------------------------
 
    # ==============================================================================
    # Apply Worksheet Format
    # ==============================================================================
    def apply_worksheet_format(
            self,
            worksheet,
            check_col,
            message_col
    ):
        """
        Apply GSPL formatting to a worksheet.

        - Copies the header style to Check and Message.
        - Sets column widths.
        - Applies thin borders to the entire used table.
        """

        # --------------------------------------------------------------------------
        # Copy Header Style
        # --------------------------------------------------------------------------

        header_source = worksheet.cell(row=1, column=check_col - 1)

        worksheet.cell(
            row=1,
            column=check_col
        )._style = copy(header_source._style)

        worksheet.cell(
            row=1,
            column=message_col
        )._style = copy(header_source._style)

        # --------------------------------------------------------------------------
        # Column Width
        # --------------------------------------------------------------------------
        worksheet.column_dimensions[
            get_column_letter(check_col)
        ].width = self.CHECK_COLUMN_WIDTH

        worksheet.column_dimensions[
            get_column_letter(message_col)
        ].width = self.MESSAGE_COLUMN_WIDTH

        # --------------------------------------------------------------------------
        # Thin Border
        # --------------------------------------------------------------------------

        thin = Side(
            border_style="thin",
            color="000000"
        )

        border = Border(
            left=thin,
            right=thin,
            top=thin,
            bottom=thin
        )

        # --------------------------------------------------------------------------
        # Apply border to the complete table
        # --------------------------------------------------------------------------

        for row in range(1, worksheet.max_row + 1):

            for col in range(1, message_col + 1):

                worksheet.cell(
                    row=row,
                    column=col
                ).border = border

    # -------------------------------------------------------------------------
    # Write Check and Messages
    # -------------------------------------------------------------------------
    def write_check_and_messages(
        self,
        worksheet,
        row,
        check_column,
        message_column,
        check,
        messages
    ):
        """
        Writes the GSPL Check and Message columns into a worksheet.
        """

        # --------------------------------------------------
        # Check
        # --------------------------------------------------

        check_cell = worksheet.cell(
            row=row,
            column=check_column
        )

        check_cell.value = check

        if check in self.check_styles:
            check_cell.fill = self.check_styles[check]

        check_cell.font = Font(bold=True)

        check_cell.alignment = Alignment(
            horizontal="center",
            vertical="center"
        )

        # --------------------------------------------------
        # Messages
        # --------------------------------------------------

        text = []

        for msg in messages:

            if isinstance(msg, dict):

                text.append(
                    f'{msg["code"]}: {msg["message"]}'
                )

            else:

                text.append(str(msg))

        message_cell = worksheet.cell(
            row=row,
            column=message_column
        )

        message_cell.value = "\n".join(text)

        message_cell.alignment = Alignment(
            wrap_text=True,
            vertical="top"
        )

        # --------------------------------------------------
        # Row Height
        # --------------------------------------------------

        lines = max(1, len(text))

        worksheet.row_dimensions[row].height = max(
            20,
            lines * 18
        )

    # -------------------------------------------------------------------------
    # Prepare Objects Sheet
    # -------------------------------------------------------------------------
    def prepare_objects_sheet(self):

        self.logger.info("")
        self.logger.info("Preparing Objects worksheet...")

        ws = self.objects_sheet

        # --------------------------------------------------
        # Find "Notes" column
        # --------------------------------------------------
        notes_col = None
        for col in range(1, ws.max_column + 1):
            value = ws.cell(row=1, column=col).value
            if value == "Notes":
                notes_col = col
                break
        if notes_col is None:
            raise RuntimeError(
                "Column 'Notes' not found in Objects worksheet."
            )

        # --------------------------------------------------
        # Insert GSPL Columns
        # --------------------------------------------------
        ws.insert_cols(notes_col + 1, amount=2)
        self.obj_col_check = notes_col + 1
        self.obj_col_message = notes_col + 2

        # --------------------------------------------------
        # Headers
        # --------------------------------------------------
        ws.cell(row=1,column=self.obj_col_check).value = "Check"
        ws.cell(row=1,column=self.obj_col_message).value = "Message"
        self.apply_worksheet_format(
            worksheet=ws,
            check_col=self.obj_col_check,
            message_col=self.obj_col_message,
        )       

        # --------------------------------------------------
        # Column Width
        # --------------------------------------------------

        ws.column_dimensions[
            get_column_letter(self.obj_col_check)
        ].width = self.CHECK_COLUMN_WIDTH

        ws.column_dimensions[
            get_column_letter(self.obj_col_message)
        ].width = self.MESSAGE_COLUMN_WIDTH

        ws.column_dimensions[
            get_column_letter(self.obj_col_message)
        ].bestFit = False

        self.logger.info(
            "Check Column   : %s",
            get_column_letter(self.obj_col_check)
        )

        self.logger.info(
            "Message Column : %s",
            get_column_letter(self.obj_col_message)
        )

        self.logger.info("OK")
 
    # -------------------------------------------------------------------------
    # Update Objects Worksheet
    # -------------------------------------------------------------------------
    def update_objects_sheet(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Updating Objects Worksheet")
        self.logger.info("========================================================")

        ws = self.objects_sheet

        updated = 0

        # --------------------------------------------------
        # Objects
        # --------------------------------------------------

        for row in range(2, ws.max_row + 1):

            component_id = ws.cell(row=row, column=1).value

            object_name = ws.cell(row=row, column=3).value

            if component_id not in self.objects:
                continue

            obj = None

            for candidate in self.objects[component_id]:

                if candidate["object_name"] == object_name:

                    obj = candidate
                    break

            if obj is None:
                continue

            # --------------------------------------------------
            # Check
            # --------------------------------------------------

            check = obj.get("check", "")

            cell = ws.cell(
                row=row,
                column=self.obj_col_check
            )

            cell.value = check

            if check in self.check_styles:

                cell.fill = self.check_styles[check]

            cell.font = Font(bold=True)

            cell.alignment = Alignment(
                horizontal="center",
                vertical="center"
            )

            # --------------------------------------------------
            # Message
            # --------------------------------------------------

            messages = []

            for msg in obj.get("messages", []):

                messages.append(

                    f'{msg["code"]}: {msg["message"]}'

                )

            message_cell = ws.cell(
                row=row,
                column=self.obj_col_message
            )

            message_cell.value = "\n".join(messages)

            message_cell.alignment = Alignment(
                wrap_text=True,
                vertical="top"
            )

            # --------------------------------------------------
            # Row Height
            # --------------------------------------------------

            lines = max(1, len(messages))

            ws.row_dimensions[row].height = max(
                20,
                lines * 18
            )

            updated += 1

        # --------------------------------------------------
        # Auto Filter
        # --------------------------------------------------

        ws.auto_filter.ref = (
            f"A1:{get_column_letter(ws.max_column)}{ws.max_row}"
        )

        # --------------------------------------------------
        # Freeze Header
        # --------------------------------------------------

        ws.freeze_panes = "A2"

        self.logger.info(
            "Objects Updated : %d",
            updated
        )

        self.logger.info("OK")

    # -------------------------------------------------------------------------
    # Normalize Object Type
    # -------------------------------------------------------------------------
    def normalize_object_type(self, object_type):
        """
        Converts the object type written by the engineer into the
        canonical internal GSPL object type.

        Examples:
            Shape              -> shape
            Dummy              -> dummy
            Vision Sensor      -> vision_sensor
            Proximity Sensor   -> proximity_sensor
        """

        if object_type is None:
            return ""

        normalized = (
            str(object_type)
            .strip()
            .lower()
            .replace(" ", "_")
        )

        return normalized

    # -------------------------------------------------------------------------
    # Generate Assembly Table
    # -------------------------------------------------------------------------
    def generate_engineering_table(self):
        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Generating Engineering Table")
        self.logger.info("========================================================")

        # --------------------------------------------------
        # Copy Engineering Table
        # --------------------------------------------------
        self.copy_assembly_table()

        # --------------------------------------------------
        # Prepare Worksheets
        # --------------------------------------------------
        self.prepare_components_sheet()
        self.prepare_objects_sheet()

        # --------------------------------------------------
        # Update Engineering Information
        # --------------------------------------------------
        self.update_components_sheet()
        self.update_objects_sheet()

        # --------------------------------------------------
        # Save Workbook
        # --------------------------------------------------
        self.save_assembly_table()
        self.logger.info("Engineering Table successfully generated.")

    # -------------------------------------------------------------------------
    # Generate Report
    # -------------------------------------------------------------------------
    def generate_report(self):

        builder = MarkdownReportBuilder(self)

        builder.generate()

    # -------------------------------------------------------------------------
    # Self Test
    # -------------------------------------------------------------------------
    def test_configuration(self):
        ok = True
        if "paths" not in self.config:
            ok = False
        if "files" not in self.config:
            ok = False
        self.logger.info(
            "[%s] Configuration",
            "PASS" if ok else "FAIL"
        )
        return ok
    def test_simulation_database(self):
        ok = True
        if "components" not in self.simulation_database:
            ok = False
        if "root" not in self.simulation_database:
            ok = False
        if "statistics" not in self.simulation_database:
            ok = False
        self.logger.info(
            "[%s] Simulation Database",
            "PASS" if ok else "FAIL"
        )
        return ok
    def test_engineering_table(self):
        filename = os.path.join(
            self.config["paths"]["database_directory"],
            self.config["files"]["assembly_table_output"]
        )
        ok = os.path.exists(filename)
        self.logger.info(
            "[%s] Engineering Table",
            "PASS" if ok else "FAIL"
        )
        return ok
    def test_markdown_report(self):
        filename = os.path.join(
            self.config["paths"]["log_directory"],
            self.config["files"]["simulation_report"]
        )
        ok = True
        if not os.path.exists(filename):
            ok = False
        elif os.path.getsize(filename) == 0:
            ok = False
        self.logger.info(
            "[%s] Markdown Report",
            "PASS" if ok else "FAIL"
        )
        return ok
    def test_statistics(self):
        ok = True
        statistics = self.simulation_database.get("statistics", {})
        components = len(
            self.simulation_database.get("components", [])
        )
        exported = statistics.get("exported", -1)
        if exported != components:
            ok = False
        enabled = statistics.get("enabled", 0)
        disabled = statistics.get("disabled", 0)
        if enabled + disabled != components:
            ok = False
        self.logger.info(
            "[%s] Statistics",
            "PASS" if ok else "FAIL"
        )
        return ok 
 
    def self_test(self):

        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" Self Test")
        self.logger.info("========================================================")

        passed = 0
        total = 0

        total += 1
        if self.test_configuration():
            passed += 1

        total += 1
        if self.test_simulation_database():
            passed += 1

        total += 1
        if self.test_engineering_table():
            passed += 1

        total += 1
        if self.test_markdown_report():
            passed += 1

        total += 1
        if self.test_statistics():
            passed += 1

        self.logger.info("")
        self.logger.info("Tests : %d/%d", passed, total)
         
        self.self_test_passed = (passed == total)

        if self.self_test_passed:
            self.logger.info("SELF TEST : PASS")
        else:
            self.logger.info("SELF TEST : FAILED")


    # -------------------------------------------------------------------------
    # Finish
    # -------------------------------------------------------------------------
    def finish(self):
        if self.audit_messages:
            self.logger.info("")
            self.logger.info("Audit Summary")
            self.logger.info("-------------")
            for audit in self.audit_messages:
                self.logger.info(str(audit))
        else:
            self.logger.info("")
            self.logger.info("No validation errors detected.")
 
        self.logger.info("")
        if self.statistics["errors"] == 0 and self.self_test_passed:
            self.logger.info("Simulation Validation: PASS")
        else:
            self.logger.info("Simulation Validation: FAIL")
        self.logger.info("")
        self.logger.info("========================================================")
        self.logger.info(" GSPL-02 Finished")
        self.logger.info("========================================================")

# =============================================================================
# Markdown Report Builder
# =============================================================================
class MarkdownReportBuilder:
    """
    Generates the GSPL-02 Simulation Report.

    This class is responsible only for formatting and writing the
    engineering report in Markdown format.

    It does not perform any validation or compilation.
    """

    # -------------------------------------------------------------------------
    # Constructor
    # -------------------------------------------------------------------------
    def __init__(self, compiler):

        self.compiler = compiler

        self.lines = []

    # -------------------------------------------------------------------------
    # Public Interface
    # -------------------------------------------------------------------------
    def generate(self):

        self.lines = []

        self._write_header()

        self._write_summary()

        self._write_statistics()

        #self._write_components()

        self._write_audits()

        self._write_footer()

        self._save()

    # -------------------------------------------------------------------------
    # Append Line
    # -------------------------------------------------------------------------
    def add(self, text=""):

        self.lines.append(text)

    # -------------------------------------------------------------------------
    # Save Report
    # -------------------------------------------------------------------------
    def _save(self):
        filename = os.path.join(
            self.compiler.config["paths"]["log_directory"],
            self.compiler.config["files"]["simulation_report"]
        )
        with open(
            filename,
            "w",
            encoding="utf-8"
        ) as f:
            f.write("\n".join(self.lines))
        self.compiler.logger.info(
            "Simulation Report : %s",
            filename
        )

    # -------------------------------------------------------------------------
    # Header
    # -------------------------------------------------------------------------
    def _write_header(self):

        self.add("# GSPL-02 Simulation Report")

        self.add()

        self.add(f"Version: {self.compiler.VERSION}")

        self.add()

    # -------------------------------------------------------------------------
    # Summary
    # -------------------------------------------------------------------------
    def _write_summary(self):

        self.add("## Summary")

        self.add()

        self.add(
            f"Components : {len(self.compiler.components)}"
        )

        object_count = sum(

            len(objects)

            for objects in self.compiler.objects.values()

        )

        self.add(
            f"Objects : {object_count}"
        )

        self.add()

    # -------------------------------------------------------------------------
    # Statistics
    # -------------------------------------------------------------------------
    def _write_statistics(self):

        self.add("## Statistics")

        self.add()

        for key, value in self.compiler.statistics.items():

            self.add(f"- {key}: {value}")

        self.add()

    # -------------------------------------------------------------------------
    # Audits
    # -------------------------------------------------------------------------
    def _write_audits(self):

        self.add("## Audit Messages")

        self.add()

        if not self.compiler.audit_messages:

            self.add("No audit messages.")

            self.add()

            return

        for msg in self.compiler.audit_messages:

            self.add(

                f"- [{msg.code}] "

                f"{msg.severity} "

                f"{msg.message}"

            )

        self.add()

    # -------------------------------------------------------------------------
    # Footer
    # -------------------------------------------------------------------------
    def _write_footer(self):

        self.add("---")

        self.add()

        self.add(
            "Generated automatically by GSPL-02 Simulation Compiler."
        )


def main():

    compiler = SimulationCompiler()

    compiler.run()

if __name__ == "__main__":

    main()